# Generated by Django 3.0.5 on 2020-07-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
                ('date_of_birth', models.DateField()),
                ('marrital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('phone', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=25)),
                ('state_of_origin', models.CharField(max_length=25)),
                ('local_government', models.CharField(max_length=25)),
                ('attatched_passport', models.ImageField(upload_to='')),
                ('degree', models.CharField(choices=[("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('PHD/PG', 'PHD/PG')], max_length=25)),
                ('status', models.CharField(choices=[('Review', 'Under Review'), ('Granted', 'Admission Granted'), ('Denied', 'Admission Denied')], default='Review', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('faculty', models.CharField(choices=[('NAS', 'Natural and Applied Science'), ('MSS', 'Management and Social Science')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WAEC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_number', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('center_number', models.CharField(max_length=25)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waec', to='core.Application', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_1', models.CharField(max_length=50)),
                ('grade_1', models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_2', models.CharField(max_length=50)),
                ('grade_2', models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_3', models.CharField(max_length=50)),
                ('grade_3', models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_4', models.CharField(max_length=50)),
                ('grade_4', models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_5', models.CharField(max_length=50)),
                ('grade_5', models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_6', models.CharField(max_length=50)),
                ('grade_6', models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_7', models.CharField(max_length=50)),
                ('grade_7', models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_8', models.CharField(blank=True, max_length=50)),
                ('grade_8', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_9', models.CharField(blank=True, max_length=50)),
                ('grade_9', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('waec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WAEC', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JAMB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('score', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jamb_score', to='core.Application', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.CreateModel(
            name='AdmissionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
