# Generated by Django 3.0.5 on 2020-07-10 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionperiod',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AlterField(
            model_name='jamb',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jamb_score', to='core.Application'),
        ),
        migrations.AlterField(
            model_name='result',
            name='waec',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.WAEC'),
        ),
        migrations.AlterField(
            model_name='waec',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waec', to='core.Application'),
        ),
    ]
